#!/usr/bin/env bash
# a Bash scrservert that will display information about subdomains.
if [ $# -eq 1 ]; then
    for sub in www lb-01 web-01 web-02; do
	subdomain="$(dig "$sub"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')"
	server="$(dig "$sub"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')"
	echo "The subdomain $sub is a $subdomain record and points to $server"
    done
elif [ $# -eq 2 ]; then
    subdomain="$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')"
    server="$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')"
    echo "The subdomain $2 is a $subdomain record and points to $server"
fi
