#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server
# Accepts 4 parameters: The IP of the server The path to the file
# The username and The path to the SSH private key
if [[ $# -ne 4 ]]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi
