#!/usr/bin/env bash
# a bash script to Install nginx on your web-01 server
apt-get -y update
apt-get -y install nginx
mv /var/www/html/index.html /var/www/html/index.txt
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
