#!/usr/bin/env bash
# a Bash script containing commands to automatically configure a Ubuntu
# machine Nginx server so that /redirect_me is redirecting to
# another page. The redirection must be a “301 Moved Permanently”
apt-get -y update
apt-get -y install nginx
mv /var/www/html/index.html /var/www/html/index.txt
echo "" > /var/www/html/index.html
redir_301=".rules\n\t\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;\n"
sed -i "s/.rules/$redir_301/" /etc/nginx/sites-available/default
sudo service nginx restart
