#!/usr/bin/env bash
# a Bash script containing commands to automatically configure a Ubuntu
# machine Nginx server so that /redirect_me is redirecting to
# another page. The redirection must be a “301 Moved Permanently”
apt-get -y update
apt-get -y install nginx
mv /var/www/html/index.html /var/www/html/index.txt
echo "" > /var/www/html/index.html
redir_404=".rules\n\t\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;\n"
sed -i "s/.rules/$redir_404/" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page\n" > /var/www/html/404.html
sed -i "s/#error_page 404 \/404.html;/error_page 404 \/404.html;/" /etc/nginx/sites-available/default
sudo service nginx restart
