#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server so that it send traffic to web-01 and web-02
apt-get -y update
apt-get -y install haproxy

sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
echo -e "\nfrontend localnodes\n\tbind *:80\n\tmode: http\n\tdefault_backend nodes\n\n\nbackend nodes\n\tbalance roundrobin\n\tserver 192892-web-01 34.207.253.67:80 check\n\tserver 192892-web-02 52.3.249.58:80 check\n" >> /etc/haproxy/haproxy.cfg
service haproxy restart
