#!/usr/bin/env bash
# keeping your Ubuntu container’s Nginx installation listening on port 80
sed -i "s/8080 default_server/80 default_server/" /etc/nginx/sites-enabled/default
service nginx restart
pkill -o nginx
