#!/usr/bin/env bash
# Bash script that displays Best School 10 times

indx=1
while [ $indx -le 10 ]
do
	if [ $indx -eq 4 ]
	then
		echo "bad luck"
	elif [ $indx -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((indx++))
done
