#!/usr/bin/env bash
# Bash script that displays Best School 10 times

indx=1
while [ $indx -le 20 ]
do
	echo $indx
	case $indx in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((indx++))
done
