#!/usr/bin/env bash
# a Bash script that gives you information about the school file

FILEschool="school"
if [ -e $FILEschool ]
then
	echo "school file exists"
	if [ -s $FILEschool ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f $FILEschool ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
